.deploy-to-test:

  stage: deploy

  variables:
    VENV_BIN: "/home/wjs/.virtualenvs/j1-venv/bin"
    PYTHON: "${VENV_BIN}/python"
    PIP: "${VENV_BIN}/pip"
    PIP_INDEX_URL: "https://gitlab.sissamedialab.it/api/v4/projects/60/packages/pypi/simple"
    # touch this file to restart the uwsgi server
    UWSGI_VASSAL: "/home/wjs/uwsgi/janeway.ini"

  script:
    - echo "Deploy to testing server"
    - chmod og= $ID_RSA
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "( $PIP install --index-url=$PIP_INDEX_URL -U $PACKAGE_NAME && cd janeway/src && $PYTHON manage.py migrate && $PYTHON manage.py build_assets && $PYTHON manage.py collectstatic --noinput && touch --no-dereference $UWSGI_VASSAL )"
